### ISSUE TITLE
gtcl ディレクトリ上にいないと urls.json が開けない仕様

### ISSUE THREAD

**Issue by konekato** [konekato/gtcl#3]
## 概要
https://github.com/konekato/gtcl/blob/68b616d433a79e71be8d0dee1cabfd384d43c03a/src/script.py#L19

**Comment by cateiru** [comment]
```py
import os

directory = os.path.dirname(__file__)
json_file_path = os.path.join(directory, 'data', 'urls.json')

urlsdict = json.load(open(json_file_path, 'r')) 
```

実行しているスクリプトのパスを取得→ディレクトリパスまでカット→そこからjsonファイルのパスにすることでどこからでも`script.py`を実行しても開けると思います。

**Comment by konekato** [comment]
@yuto51942 コントリビューションありがとうございます🙏
助かりました！

**Comment by konekato** [comment]
#7 にて解決。
クローズ。
